settings = {'animrange': ['1', '24', '1'],
			'animtype': True,
			'asnurmbs': True,
			'colornaming': 1,
			'curvgrp_layer': [False, '', 'LAYER_'],
			'curvgrp_obj': [False, '', 'OBJ_'],
			'curvgrp_par': [False, '', 'PAR_'],
			'expHi': True,
			'expanim': False,
			'expcolor': False,
			'expcrease': False,
			'expcurve': True,
			'expcurveglobEnable': True,
			'expcurveglobname': 'CURV',
			'expgeogrp_layer': [False, '', 'LAYER_'],
			'expgeogrp_mtl': [False, '', 'MTL_'],
			'expgeogrp_obj': [False, '', 'OBJ_'],
			'expgeogrp_parent': [False, '', 'PRNT_'],
			'expgeogrp_shp': [False, '', 'SHAPE_'],
			'exportgeo': True,
			'exportpath': '',
			'exppartattrib': [False, ''],
			'exppartgrp_emit': [False, '', 'EMITTER_'],
			'exppartgrp_shape': [False, '', 'OBJ_'],
			'expparticle': True,
			'expparticlglobEnable': True,
			'expparticlglobname': 'PART',
			'exppiv': False,
			'exppivattrib': [False, ''],
			'exppivfilter': '',
			'exppivgrp_obj': [False, '', 'OBJ_'],
			'exppivgrp_parent': [False, '', 'PAR_'],
			'exppivgrp_shape': [False, '', 'INSTATCE_'],
			'exppivgrp_layer': [False, '', 'LAYER_'],
			'exppivorient': True,
			'exppivotglobEnable': True,
			'exppivotglobname': 'PIVOT',
			'exppivscale': True,
			'exppivskipnoshape': True,
			'expuv': True,
			'expvertexnorm': False,
			'expvis': False,
			'fileExists': 1,
			'fileformat': True,
			'geocustomattr': [False, ''],
			'geoglobalEnable': True,
			'geoglobalname': 'POLY',
			'globalpos': True,
			'gzip': False,
			'scale': 1.0,
			'uvnaming': 1,
			'writefile': True,
			}